### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by SamWanDev** [Vanamo/Krypto#1]
Vertaisarviointi Krypto-ohjelmasta (ladattu keskiviikkona 10.2.2018 klo 12:00)

Koodi on selkeää ja luokat jaoteltu hyvin. Varsinkin sanalistan lukeminen tiedostosta oli mielestäni toteuttettu melko mallikkaasti! Koodin sekaan oli kuitenkin jäänyt vähän turhan paljon pois kommentoituja rivejä, jotka voisi siivota pois. Githubiin voisi myös lisätä lyhyet käyttöohjeet.

CrosswordMaker.getRandomWord metodi on toteutettu melko kömpelösti, sillä eikö se jää jumiin jos esimerkiksi lista ei sisällä yhtään halutun pituista sanaa? Suosittelisin järjestämään sanalistan sanan pituuden perusteella, jolloin tietyn pituisen sanan löytäminen muuttuu huomattavasti helpommaksi. makeWordLengthStatistics metodi ilmeisesti jo tekee tarvittavan työn, joten ehkä kannattaisi muuttaa metodia niin että se ottaisi keräämänsä tiedon paremmin talteen?

Koodi päättyy vähän turhan virheilmoitukseen ettei ratkaisua löytynyt, vaikka aloitussanan jättäisi tyhjäksi. Oletko miettinyt että ohjelma ohjelma yrittäisi krypton luomista vaikka luupilla muutaman kerran ennen virheilmoituksen antamista?

**Comment by Vanamo** [comment]
Kiitos kommenteista :) Parantelin nyt tuota getRandomWord-metodia. Käyttöliittymää aion myös vielä muuttaa.
